//
// Temporary route in app. This wil need moving to service cache if used.
//

const data = {
  type: 'FeatureCollection',
  features: [
    { type: 'Feature', properties: { n: 'London', d: 1, s: 1 }, geometry: { type: 'Point', coordinates: [-0.13, 51.51] } },
    { type: 'Feature', properties: { n: 'Birmingham', d: 1, s: 1 }, geometry: { type: 'Point', coordinates: [-1.90, 52.48] } },
    { type: 'Feature', properties: { n: 'Leeds', d: 2, s: 1 }, geometry: { type: 'Point', coordinates: [-1.55, 53.80] } },
    { type: 'Feature', properties: { n: 'Glasgow', d: 6, s: 1 }, geometry: { type: 'Point', coordinates: [-4.25, 55.86] } },
    { type: 'Feature', properties: { n: 'Manchester', d: 1, s: 1 }, geometry: { type: 'Point', coordinates: [-2.25, 53.48] } },
    { type: 'Feature', properties: { n: 'Sheffield', d: 3, s: 1 }, geometry: { type: 'Point', coordinates: [-1.47, 53.38] } },
    { type: 'Feature', properties: { n: 'Liverpool', d: 3, s: 1 }, geometry: { type: 'Point', coordinates: [-2.98, 53.40] } },
    { type: 'Feature', properties: { n: 'Edinburgh', d: 6, s: 1 }, geometry: { type: 'Point', coordinates: [-3.19, 55.95] } },
    { type: 'Feature', properties: { n: 'Bristol', d: 1, s: 1 }, geometry: { type: 'Point', coordinates: [-2.58, 51.45] } },
    { type: 'Feature', properties: { n: 'Coventry', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-1.51, 52.41] } },
    { type: 'Feature', properties: { n: 'Cardiff', d: -1, s: 3 }, geometry: { type: 'Point', coordinates: [-3.18, 51.48] } },
    { type: 'Feature', properties: { n: 'Belfast', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-5.93, 54.60] } },
    { type: 'Feature', properties: { n: 'Leicester', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-1.13, 52.63] } },
    { type: 'Feature', properties: { n: 'Nottingham', d: 2, s: 3 }, geometry: { type: 'Point', coordinates: [-1.15, 52.95] } },
    { type: 'Feature', properties: { n: 'Southampton', d: 2, s: 3 }, geometry: { type: 'Point', coordinates: [-1.40, 50.90] } },
    { type: 'Feature', properties: { n: 'Newcastle', d: 1, s: 1 }, geometry: { type: 'Point', coordinates: [-1.66, 55.01] } },
    { type: 'Feature', properties: { n: 'Plymouth', d: 1, s: 3 }, geometry: { type: 'Point', coordinates: [-4.14, 50.37] } },
    { type: 'Feature', properties: { n: 'Hull', d: 2, s: 3 }, geometry: { type: 'Point', coordinates: [-0.33, 53.74] } },
    { type: 'Feature', properties: { n: 'Wolverhampton', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-2.13, 52.58] } },
    { type: 'Feature', properties: { n: 'Stoke-on-Trent', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-2.18, 53.00] } },
    { type: 'Feature', properties: { n: 'Derby', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-1.47, 52.92] } },
    { type: 'Feature', properties: { n: 'Swansea', d: -1, s: 3 }, geometry: { type: 'Point', coordinates: [-3.95, 51.62] } },
    { type: 'Feature', properties: { n: 'Portsmouth', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-1.09, 50.81] } },
    { type: 'Feature', properties: { n: 'Reading', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-0.97, 51.45] } },
    { type: 'Feature', properties: { n: 'Aberdeen', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-2.11, 57.15] } },
    { type: 'Feature', properties: { n: 'Luton', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-0.41, 51.88] } },
    { type: 'Feature', properties: { n: 'Northampton', d: 2, s: 3 }, geometry: { type: 'Point', coordinates: [-0.89, 52.23] } },
    { type: 'Feature', properties: { n: 'Milton Keynes', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-0.76, 52.04] } },
    { type: 'Feature', properties: { n: 'Peterborough', d: 2, s: 3 }, geometry: { type: 'Point', coordinates: [-0.25, 52.58] } },
    { type: 'Feature', properties: { n: 'Norwich', d: 1, s: 3 }, geometry: { type: 'Point', coordinates: [1.30, 52.63] } },
    { type: 'Feature', properties: { n: 'Croydon', d: -1, s: 3 }, geometry: { type: 'Point', coordinates: [-0.11, 51.37] } },
    { type: 'Feature', properties: { n: 'Basildon', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [0.49, 51.58] } },
    { type: 'Feature', properties: { n: 'Bournemouth', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-1.88, 50.72] } },
    { type: 'Feature', properties: { n: 'Swindon', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-1.78, 51.56] } },
    { type: 'Feature', properties: { n: 'Ipswich', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [1.16, 52.06] } },
    { type: 'Feature', properties: { n: 'Sunderland', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-1.38, 54.91] } },
    { type: 'Feature', properties: { n: 'Ilford', d: -1, s: 3 }, geometry: { type: 'Point', coordinates: [0.09, 51.56] } },
    { type: 'Feature', properties: { n: 'Warrington', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-2.60, 53.39] } },
    { type: 'Feature', properties: { n: 'Huddersfield', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-1.78, 53.65] } },
    { type: 'Feature', properties: { n: 'York', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-1.08, 53.96] } },
    { type: 'Feature', properties: { n: 'Oxford', d: 2, s: 3 }, geometry: { type: 'Point', coordinates: [-1.26, 51.75] } },
    { type: 'Feature', properties: { n: 'Harrow', d: 5, s: 3 }, geometry: { type: 'Point', coordinates: [-0.35, 51.58] } },
    { type: 'Feature', properties: { n: 'Dundee', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-2.97, 56.46] } },
    { type: 'Feature', properties: { n: 'Poole', d: 5, s: 3 }, geometry: { type: 'Point', coordinates: [-1.98, 50.72] } },
    { type: 'Feature', properties: { n: 'Telford', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-2.45, 52.68] } },
    { type: 'Feature', properties: { n: 'Middlesbrough', d: 2, s: 3 }, geometry: { type: 'Point', coordinates: [-1.24, 54.58] } },
    { type: 'Feature', properties: { n: 'Blackpool', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-3.05, 53.81] } },
    { type: 'Feature', properties: { n: 'Brighton', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-0.13, 50.84] } },
    { type: 'Feature', properties: { n: 'Sale', d: 5, s: 3 }, geometry: { type: 'Point', coordinates: [-2.32, 53.42] } },
    { type: 'Feature', properties: { n: 'Enfield', d: 5, s: 3 }, geometry: { type: 'Point', coordinates: [-0.08, 51.65] } },
    { type: 'Feature', properties: { n: 'Tottenham', d: 5, s: 3 }, geometry: { type: 'Point', coordinates: [-0.07, 51.59] } },
    { type: 'Feature', properties: { n: 'Bolton', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-2.43, 53.58] } },
    { type: 'Feature', properties: { n: 'Newport', d: -1, s: 3 }, geometry: { type: 'Point', coordinates: [-3.00, 51.58] } },
    { type: 'Feature', properties: { n: 'Cambridge', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [0.12, 52.21] } },
    { type: 'Feature', properties: { n: 'Exeter', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-3.53, 50.72] } },
    { type: 'Feature', properties: { n: 'Solihull', d: -1, s: 3 }, geometry: { type: 'Point', coordinates: [-1.78, 52.41] } },
    { type: 'Feature', properties: { n: 'Romford', d: -1, s: 3 }, geometry: { type: 'Point', coordinates: [0.18, 51.58] } },
    { type: 'Feature', properties: { n: 'Preston', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-2.70, 53.76] } },
    { type: 'Feature', properties: { n: 'High Wycombe', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-0.75, 51.63] } },
    { type: 'Feature', properties: { n: 'Gateshead', d: 5, s: 3 }, geometry: { type: 'Point', coordinates: [-1.60, 54.95] } },
    { type: 'Feature', properties: { n: 'Slough', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-0.59, 51.51] } },
    { type: 'Feature', properties: { n: 'Blackburn', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-2.48, 53.75] } },
    { type: 'Feature', properties: { n: 'Cheltenham', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-2.07, 51.90] } },
    { type: 'Feature', properties: { n: 'Colchester', d: 2, s: 3 }, geometry: { type: 'Point', coordinates: [0.90, 51.89] } },
    { type: 'Feature', properties: { n: 'Chelmsford', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [0.48, 51.74] } },
    { type: 'Feature', properties: { n: 'Wythenshawe', d: 6, s: 3 }, geometry: { type: 'Point', coordinates: [-2.26, 53.39] } },
    { type: 'Feature', properties: { n: 'Doncaster', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-1.13, 53.52] } },
    { type: 'Feature', properties: { n: 'Rotherham', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-1.36, 53.43] } },
    { type: 'Feature', properties: { n: 'Walthamstow', d: 5, s: 3 }, geometry: { type: 'Point', coordinates: [0.00, 51.59] } },
    { type: 'Feature', properties: { n: 'Worthing', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-0.37, 50.81] } },
    { type: 'Feature', properties: { n: 'Rochdale', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-2.16, 53.61] } },
    { type: 'Feature', properties: { n: 'Maidstone', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [0.53, 51.27] } },
    { type: 'Feature', properties: { n: 'Basingstoke', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-1.09, 51.27] } },
    { type: 'Feature', properties: { n: 'Crawley', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-0.19, 51.11] } },
    { type: 'Feature', properties: { n: 'Dagenham', d: 5, s: 3 }, geometry: { type: 'Point', coordinates: [0.14, 51.54] } },
    { type: 'Feature', properties: { n: 'Stockport', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-2.15, 53.41] } },
    { type: 'Feature', properties: { n: 'Fyfield', d: 5, s: 3 }, geometry: { type: 'Point', coordinates: [0.27, 51.74] } },
    { type: 'Feature', properties: { n: 'Gillingham', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [0.55, 51.39] } },
    { type: 'Feature', properties: { n: 'Salford', d: -1, s: 3 }, geometry: { type: 'Point', coordinates: [-2.29, 53.48] } },
    { type: 'Feature', properties: { n: 'Wigan', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-2.63, 53.54] } },
    { type: 'Feature', properties: { n: 'Hounslow', d: 5, s: 3 }, geometry: { type: 'Point', coordinates: [-0.38, 51.47] } },
    { type: 'Feature', properties: { n: 'Saint Helens', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [-2.75, 53.45] } },
    { type: 'Feature', properties: { n: 'Eastbourne', d: 4, s: 3 }, geometry: { type: 'Point', coordinates: [0.28, 50.77] } },
    { type: 'Feature', properties: { n: 'Worcester', d: 3, s: 3 }, geometry: { type: 'Point', coordinates: [-2.22, 52.19] } },
    { type: 'Feature', properties: { n: 'Wakefield', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.49, 53.68] } },
    { type: 'Feature', properties: { n: 'Lincoln', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-0.54, 53.23] } },
    { type: 'Feature', properties: { n: 'Oldham', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.12, 53.54] } },
    { type: 'Feature', properties: { n: 'Sutton Coldfield', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-1.82, 52.56] } },
    { type: 'Feature', properties: { n: 'Hemel Hempstead', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.47, 51.75] } },
    { type: 'Feature', properties: { n: 'Bedford', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-0.47, 52.14] } },
    { type: 'Feature', properties: { n: 'Darlington', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.55, 54.53] } },
    { type: 'Feature', properties: { n: 'Hove', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.18, 50.84] } },
    { type: 'Feature', properties: { n: 'Barnsley', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.48, 53.55] } },
    { type: 'Feature', properties: { n: 'Hastings', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [0.57, 50.85] } },
    { type: 'Feature', properties: { n: 'Southport', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-3.01, 53.65] } },
    { type: 'Feature', properties: { n: 'Watford', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-0.40, 51.66] } },
    { type: 'Feature', properties: { n: 'Wembley', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.30, 51.55] } },
    { type: 'Feature', properties: { n: 'Bath', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.36, 51.38] } },
    { type: 'Feature', properties: { n: 'Hartlepool', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.21, 54.69] } },
    { type: 'Feature', properties: { n: 'Birkenhead', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-3.01, 53.39] } },
    { type: 'Feature', properties: { n: 'Grimsby', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-0.07, 53.56] } },
    { type: 'Feature', properties: { n: 'Halifax', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.86, 53.73] } },
    { type: 'Feature', properties: { n: 'Bromley', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [0.02, 51.41] } },
    { type: 'Feature', properties: { n: 'Fulham', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.20, 51.48] } },
    { type: 'Feature', properties: { n: 'Nuneaton', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.47, 52.52] } },
    { type: 'Feature', properties: { n: 'Ealing', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.30, 51.52] } },
    { type: 'Feature', properties: { n: 'Woolwich', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [0.06, 51.49] } },
    { type: 'Feature', properties: { n: 'Hayes', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.42, 51.51] } },
    { type: 'Feature', properties: { n: 'Stockton-on-Tees', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-1.32, 54.57] } },
    { type: 'Feature', properties: { n: 'Edmonton', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.07, 51.62] } },
    { type: 'Feature', properties: { n: 'Saint Albans', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-0.34, 51.76] } },
    { type: 'Feature', properties: { n: 'Harlow', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [0.13, 51.78] } },
    { type: 'Feature', properties: { n: 'Redditch', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.95, 52.31] } },
    { type: 'Feature', properties: { n: 'Derry', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-7.33, 55.00] } },
    { type: 'Feature', properties: { n: 'Scunthorpe', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-0.65, 53.58] } },
    { type: 'Feature', properties: { n: 'Chester', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.89, 53.19] } },
    { type: 'Feature', properties: { n: 'Dudley', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.09, 52.51] } },
    { type: 'Feature', properties: { n: 'Bury', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.30, 53.59] } },
    { type: 'Feature', properties: { n: 'Brixton', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.11, 51.46] } },
    { type: 'Feature', properties: { n: 'West Bromwich', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.00, 52.52] } },
    { type: 'Feature', properties: { n: 'Mansfield', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.20, 53.15] } },
    { type: 'Feature', properties: { n: 'Bracknell', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.75, 51.42] } },
    { type: 'Feature', properties: { n: 'Guildford', d: 3, s: 4 }, geometry: { type: 'Point', coordinates: [-0.57, 51.24] } },
    { type: 'Feature', properties: { n: 'Chatham', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [0.52, 51.37] } },
    { type: 'Feature', properties: { n: 'Edgware', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.27, 51.62] } },
    { type: 'Feature', properties: { n: 'Paisley', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-4.42, 55.85] } },
    { type: 'Feature', properties: { n: 'East Ham', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [0.06, 51.53] } },
    { type: 'Feature', properties: { n: 'Weston-super-Mare', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.98, 51.35] } },
    { type: 'Feature', properties: { n: 'South Shields', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-1.43, 55.00] } },
    { type: 'Feature', properties: { n: 'Carlisle', d: 2, s: 4 }, geometry: { type: 'Point', coordinates: [-2.94, 54.89] } },
    { type: 'Feature', properties: { n: 'Newcastle under Lyme', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.23, 53.01] } },
    { type: 'Feature', properties: { n: 'East Kilbride', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-4.18, 55.76] } },
    { type: 'Feature', properties: { n: 'Harrogate', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.54, 53.99] } },
    { type: 'Feature', properties: { n: 'Burnley', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.25, 53.79] } },
    { type: 'Feature', properties: { n: 'Burton upon Trent', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.64, 52.80] } },
    { type: 'Feature', properties: { n: 'Crewe', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.44, 53.10] } },
    { type: 'Feature', properties: { n: 'Shrewsbury', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.75, 52.71] } },
    { type: 'Feature', properties: { n: 'Gosport', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-1.12, 50.79] } },
    { type: 'Feature', properties: { n: 'Lisburn', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-6.03, 54.52] } },
    { type: 'Feature', properties: { n: 'Lowestoft', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [1.75, 52.48] } },
    { type: 'Feature', properties: { n: 'Rugby', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.26, 52.37] } },
    { type: 'Feature', properties: { n: 'Uxbridge', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.48, 51.54] } },
    { type: 'Feature', properties: { n: 'Southall', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.38, 51.51] } },
    { type: 'Feature', properties: { n: 'Stafford', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.12, 52.81] } },
    { type: 'Feature', properties: { n: 'Wimbledon', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.21, 51.42] } },
    { type: 'Feature', properties: { n: 'Walsall', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-1.98, 52.58] } },
    { type: 'Feature', properties: { n: 'Ashford', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [0.87, 51.15] } },
    { type: 'Feature', properties: { n: 'Tynemouth', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-1.42, 55.02] } },
    { type: 'Feature', properties: { n: 'Washington', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-1.52, 54.90] } },
    { type: 'Feature', properties: { n: 'Chingford', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [0.02, 51.63] } },
    { type: 'Feature', properties: { n: 'Gravesend', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [0.37, 51.44] } },
    { type: 'Feature', properties: { n: 'Thornton Heath', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.11, 51.40] } },
    { type: 'Feature', properties: { n: 'Finchley', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.19, 51.60] } },
    { type: 'Feature', properties: { n: 'Torquay', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-3.53, 50.47] } },
    { type: 'Feature', properties: { n: 'Farnborough', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.75, 51.29] } },
    { type: 'Feature', properties: { n: 'Kensington', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.19, 51.50] } },
    { type: 'Feature', properties: { n: 'Waterlooville', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-1.03, 50.88] } },
    { type: 'Feature', properties: { n: 'Inverness', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-4.22, 57.48] } },
    { type: 'Feature', properties: { n: 'Hornchurch', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [0.21, 51.56] } },
    { type: 'Feature', properties: { n: 'Maidenhead', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.72, 51.52] } },
    { type: 'Feature', properties: { n: 'Mitcham', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.15, 51.40] } },
    { type: 'Feature', properties: { n: 'Feltham', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.41, 51.45] } },
    { type: 'Feature', properties: { n: 'Stourbridge', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.15, 52.46] } },
    { type: 'Feature', properties: { n: 'Rochester', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [0.50, 51.38] } },
    { type: 'Feature', properties: { n: 'Dewsbury', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-1.63, 53.69] } },
    { type: 'Feature', properties: { n: 'Woking', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.56, 51.32] } },
    { type: 'Feature', properties: { n: 'Sittingbourne', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [0.74, 51.34] } },
    { type: 'Feature', properties: { n: 'Acton', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.27, 51.51] } },
    { type: 'Feature', properties: { n: 'Twickenham', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.34, 51.45] } },
    { type: 'Feature', properties: { n: 'Runcorn', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.73, 53.34] } },
    { type: 'Feature', properties: { n: 'Scarborough', d: 3, s: 4 }, geometry: { type: 'Point', coordinates: [-0.40, 54.28] } },
    { type: 'Feature', properties: { n: 'Wrexham', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.99, 53.05] } },
    { type: 'Feature', properties: { n: 'Wandsworth', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.19, 51.46] } },
    { type: 'Feature', properties: { n: 'Widnes', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.73, 53.36] } },
    { type: 'Feature', properties: { n: 'Margate', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [1.38, 51.39] } },
    { type: 'Feature', properties: { n: 'Bangor', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-5.67, 54.66] } },
    { type: 'Feature', properties: { n: 'Taunton', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-3.10, 51.02] } },
    { type: 'Feature', properties: { n: 'Wallasey', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-3.02, 53.42] } },
    { type: 'Feature', properties: { n: 'Loughborough', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.20, 52.77] } },
    { type: 'Feature', properties: { n: 'Barking', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [0.08, 51.54] } },
    { type: 'Feature', properties: { n: 'Aylesbury', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-0.81, 51.82] } },
    { type: 'Feature', properties: { n: 'Ruislip', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.43, 51.58] } },
    { type: 'Feature', properties: { n: 'Halesowen', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.05, 52.45] } },
    { type: 'Feature', properties: { n: 'Streatham', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.12, 51.43] } },
    { type: 'Feature', properties: { n: 'Royal Tunbridge Wells', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [0.26, 51.13] } },
    { type: 'Feature', properties: { n: 'Barrow in Furness', d: 2, s: 4 }, geometry: { type: 'Point', coordinates: [-3.23, 54.11] } },
    { type: 'Feature', properties: { n: 'Kettering', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-0.72, 52.39] } },
    { type: 'Feature', properties: { n: 'Hereford', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.72, 52.06] } },
    { type: 'Feature', properties: { n: 'Ellesmere Port', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.90, 53.28] } },
    { type: 'Feature', properties: { n: 'Kidderminster', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.25, 52.39] } },
    { type: 'Feature', properties: { n: 'Corby', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-0.70, 52.49] } },
    { type: 'Feature', properties: { n: 'Canterbury', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [1.08, 51.28] } },
    { type: 'Feature', properties: { n: 'Braintree', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [0.55, 51.88] } },
    { type: 'Feature', properties: { n: 'Keighley', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-1.91, 53.87] } },
    { type: 'Feature', properties: { n: 'Hamilton', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-4.04, 55.78] } },
    { type: 'Feature', properties: { n: 'Weymouth', d: 2, s: 4 }, geometry: { type: 'Point', coordinates: [-2.46, 50.61] } },
    { type: 'Feature', properties: { n: 'Hendon', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.23, 51.58] } },
    { type: 'Feature', properties: { n: 'Altrincham', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.35, 53.38] } },
    { type: 'Feature', properties: { n: 'Lancaster', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.80, 54.05] } },
    { type: 'Feature', properties: { n: 'Barry', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-3.27, 51.41] } },
    { type: 'Feature', properties: { n: 'Macclesfield', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-2.13, 53.26] } },
    { type: 'Feature', properties: { n: 'Bootle', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.99, 53.45] } },
    { type: 'Feature', properties: { n: 'Stratford', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.00, 51.54] } },
    { type: 'Feature', properties: { n: 'Horsham', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-0.33, 51.06] } },
    { type: 'Feature', properties: { n: 'Livingston', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-3.52, 55.88] } },
    { type: 'Feature', properties: { n: 'Clacton-on-Sea', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [1.15, 51.79] } },
    { type: 'Feature', properties: { n: 'Cumbernauld', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-3.99, 55.95] } },
    { type: 'Feature', properties: { n: 'Dunfermline', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-3.44, 56.07] } },
    { type: 'Feature', properties: { n: 'Rowley Regis', d: -1, s: 4 }, geometry: { type: 'Point', coordinates: [-2.06, 52.48] } },
    { type: 'Feature', properties: { n: 'Crosby', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-3.03, 53.49] } },
    { type: 'Feature', properties: { n: 'Leith', d: 4, s: 4 }, geometry: { type: 'Point', coordinates: [-3.17, 55.98] } },
    { type: 'Feature', properties: { n: 'Royal Leamington Spa', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.54, 52.29] } },
    { type: 'Feature', properties: { n: 'Brentwood', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [0.31, 51.62] } },
    { type: 'Feature', properties: { n: 'Batley', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.63, 53.72] } },
    { type: 'Feature', properties: { n: 'Pen-y-Bont ar Ogwr', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-3.58, 51.51] } },
    { type: 'Feature', properties: { n: 'Wellingborough', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.70, 52.29] } },
    { type: 'Feature', properties: { n: 'Sutton in Ashfield', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.26, 53.13] } },
    { type: 'Feature', properties: { n: 'Paignton', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-3.56, 50.44] } },
    { type: 'Feature', properties: { n: 'Eltham', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [0.05, 51.45] } },
    { type: 'Feature', properties: { n: 'Cwmbran', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-3.02, 51.65] } },
    { type: 'Feature', properties: { n: 'Christchurch', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.78, 50.73] } },
    { type: 'Feature', properties: { n: 'Morden', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.19, 51.40] } },
    { type: 'Feature', properties: { n: 'Kirkcaldy', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-3.17, 56.11] } },
    { type: 'Feature', properties: { n: 'Durham', d: 3, s: 5 }, geometry: { type: 'Point', coordinates: [-1.57, 54.78] } },
    { type: 'Feature', properties: { n: 'Barnet', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.20, 51.64] } },
    { type: 'Feature', properties: { n: 'West Bridgford', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.13, 52.93] } },
    { type: 'Feature', properties: { n: 'Stretford', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-2.31, 53.45] } },
    { type: 'Feature', properties: { n: 'Banbury', d: 4, s: 5 }, geometry: { type: 'Point', coordinates: [-1.34, 52.06] } },
    { type: 'Feature', properties: { n: 'Beckenham', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.02, 51.41] } },
    { type: 'Feature', properties: { n: 'Greenford', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.35, 51.53] } },
    { type: 'Feature', properties: { n: 'Wokingham', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.84, 51.41] } },
    { type: 'Feature', properties: { n: 'Folkestone', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [1.17, 51.08] } },
    { type: 'Feature', properties: { n: 'Welwyn Garden City', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.19, 51.81] } },
    { type: 'Feature', properties: { n: 'Ayr', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-4.63, 55.46] } },
    { type: 'Feature', properties: { n: 'Kilmarnock', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-4.50, 55.61] } },
    { type: 'Feature', properties: { n: 'Havant', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.98, 50.85] } },
    { type: 'Feature', properties: { n: 'Chippenham', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-2.12, 51.46] } },
    { type: 'Feature', properties: { n: 'Erith', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [0.18, 51.48] } },
    { type: 'Feature', properties: { n: 'Hinckley', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.37, 52.54] } },
    { type: 'Feature', properties: { n: 'Ashton', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-2.10, 53.49] } },
    { type: 'Feature', properties: { n: 'Surbiton', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.31, 51.39] } },
    { type: 'Feature', properties: { n: 'Yeovil', d: 3, s: 5 }, geometry: { type: 'Point', coordinates: [-2.64, 50.95] } },
    { type: 'Feature', properties: { n: 'Catford', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.02, 51.45] } },
    { type: 'Feature', properties: { n: 'Morley', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.60, 53.75] } },
    { type: 'Feature', properties: { n: 'Cheshunt', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.04, 51.70] } },
    { type: 'Feature', properties: { n: 'Coatbridge', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-4.03, 55.86] } },
    { type: 'Feature', properties: { n: 'Wallsend', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.53, 54.99] } },
    { type: 'Feature', properties: { n: 'Merthyr Tydfil', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-3.38, 51.74] } },
    { type: 'Feature', properties: { n: 'Bexhill', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [0.47, 50.84] } },
    { type: 'Feature', properties: { n: 'Perth', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-3.44, 56.40] } },
    { type: 'Feature', properties: { n: 'Sidcup', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [0.10, 51.43] } },
    { type: 'Feature', properties: { n: 'Kingston upon Thames', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.30, 51.41] } },
    { type: 'Feature', properties: { n: 'Middleton', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-2.19, 53.56] } },
    { type: 'Feature', properties: { n: 'King’s Lynn', d: 3, s: 5 }, geometry: { type: 'Point', coordinates: [0.40, 52.75] } },
    { type: 'Feature', properties: { n: 'Fareham', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.18, 50.85] } },
    { type: 'Feature', properties: { n: 'Greenock', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-4.77, 55.95] } },
    { type: 'Feature', properties: { n: 'Urmston', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-2.37, 53.45] } },
    { type: 'Feature', properties: { n: 'Worksop', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.12, 53.30] } },
    { type: 'Feature', properties: { n: 'Sutton', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-0.20, 51.37] } },
    { type: 'Feature', properties: { n: 'Caerphilly', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-3.22, 51.58] } },
    { type: 'Feature', properties: { n: 'Bridgwater', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-2.99, 51.13] } },
    { type: 'Feature', properties: { n: 'Leigh', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-2.52, 53.50] } },
    { type: 'Feature', properties: { n: 'Newbury', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.32, 51.40] } },
    { type: 'Feature', properties: { n: 'Welling', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [0.11, 51.46] } },
    { type: 'Feature', properties: { n: 'Kingswood', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-2.51, 51.46] } },
    { type: 'Feature', properties: { n: 'Bury Saint Edmunds', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [0.72, 52.25] } },
    { type: 'Feature', properties: { n: 'Kirkby', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-2.89, 53.48] } },
    { type: 'Feature', properties: { n: 'Ramsgate', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [1.42, 51.34] } },
    { type: 'Feature', properties: { n: 'Salisbury', d: 3, s: 5 }, geometry: { type: 'Point', coordinates: [-1.79, 51.07] } },
    { type: 'Feature', properties: { n: 'Castleford', d: 5, s: 5 }, geometry: { type: 'Point', coordinates: [-1.36, 53.72] } },
    { type: 'Feature', properties: { n: 'Aberdare', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.45, 51.71] } },
    { type: 'Feature', properties: { n: 'Farnham', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.80, 51.22] } },
    { type: 'Feature', properties: { n: 'Hatfield', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.23, 51.76] } },
    { type: 'Feature', properties: { n: 'Cleethorpes', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.02, 53.55] } },
    { type: 'Feature', properties: { n: 'Skelmersdale', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.78, 53.55] } },
    { type: 'Feature', properties: { n: 'Tipton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.08, 52.53] } },
    { type: 'Feature', properties: { n: 'Eccles', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.34, 53.48] } },
    { type: 'Feature', properties: { n: 'Great Yarmouth', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [1.73, 52.61] } },
    { type: 'Feature', properties: { n: 'Tonbridge', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.28, 51.20] } },
    { type: 'Feature', properties: { n: 'Ilkeston', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.31, 52.97] } },
    { type: 'Feature', properties: { n: 'Herne Bay', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [1.13, 51.37] } },
    { type: 'Feature', properties: { n: 'Andover', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-1.48, 51.21] } },
    { type: 'Feature', properties: { n: 'Glenrothes', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.18, 56.20] } },
    { type: 'Feature', properties: { n: 'Bishops Stortford', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.17, 51.87] } },
    { type: 'Feature', properties: { n: 'Camberley', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.74, 51.34] } },
    { type: 'Feature', properties: { n: 'Stirling', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.94, 56.12] } },
    { type: 'Feature', properties: { n: 'Arnold', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.13, 53.01] } },
    { type: 'Feature', properties: { n: 'Long Eaton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.27, 52.90] } },
    { type: 'Feature', properties: { n: 'Blyth', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.51, 55.13] } },
    { type: 'Feature', properties: { n: 'Port Talbot', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.80, 51.59] } },
    { type: 'Feature', properties: { n: 'Bletchley', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.73, 51.99] } },
    { type: 'Feature', properties: { n: 'Llanelli', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-4.16, 51.68] } },
    { type: 'Feature', properties: { n: 'Leighton Buzzard', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.66, 51.92] } },
    { type: 'Feature', properties: { n: 'Fleet', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.85, 51.28] } },
    { type: 'Feature', properties: { n: 'Beeston', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.22, 52.93] } },
    { type: 'Feature', properties: { n: 'Small Heath', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.85, 52.46] } },
    { type: 'Feature', properties: { n: 'Houghton le Spring', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.47, 54.84] } },
    { type: 'Feature', properties: { n: 'Whitley Bay', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.44, 55.05] } },
    { type: 'Feature', properties: { n: 'Airdrie', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.98, 55.86] } },
    { type: 'Feature', properties: { n: 'Grays', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.33, 51.48] } },
    { type: 'Feature', properties: { n: 'Denton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.11, 53.46] } },
    { type: 'Feature', properties: { n: 'Aldershot', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.76, 51.25] } },
    { type: 'Feature', properties: { n: 'Redcar', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.07, 54.62] } },
    { type: 'Feature', properties: { n: 'Walkden', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.40, 53.52] } },
    { type: 'Feature', properties: { n: 'Kenton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.31, 51.59] } },
    { type: 'Feature', properties: { n: 'Leyland', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.70, 53.69] } },
    { type: 'Feature', properties: { n: 'Woodley', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.90, 51.45] } },
    { type: 'Feature', properties: { n: 'Accrington', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.36, 53.75] } },
    { type: 'Feature', properties: { n: 'Pont-y-pŵl', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.04, 51.70] } },
    { type: 'Feature', properties: { n: 'Bridlington', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-0.19, 54.08] } },
    { type: 'Feature', properties: { n: 'Winchester', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-1.31, 51.06] } },
    { type: 'Feature', properties: { n: 'Falkirk', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.78, 56.00] } },
    { type: 'Feature', properties: { n: 'Billingham', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.27, 54.61] } },
    { type: 'Feature', properties: { n: 'Boston', d: 2, s: 6 }, geometry: { type: 'Point', coordinates: [-0.02, 52.97] } },
    { type: 'Feature', properties: { n: 'Dunstable', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.52, 51.89] } },
    { type: 'Feature', properties: { n: 'Ewell', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.25, 51.35] } },
    { type: 'Feature', properties: { n: 'Morecambe', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.87, 54.07] } },
    { type: 'Feature', properties: { n: 'Chorley', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.63, 53.65] } },
    { type: 'Feature', properties: { n: 'Spalding', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.15, 52.79] } },
    { type: 'Feature', properties: { n: 'Grantham', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.64, 52.92] } },
    { type: 'Feature', properties: { n: 'Exmouth', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.41, 50.62] } },
    { type: 'Feature', properties: { n: 'North Shields', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.44, 55.01] } },
    { type: 'Feature', properties: { n: 'Colwyn Bay', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.70, 53.29] } },
    { type: 'Feature', properties: { n: 'Hyde', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.08, 53.45] } },
    { type: 'Feature', properties: { n: 'Wisbech', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.16, 52.66] } },
    { type: 'Feature', properties: { n: 'Lichfield', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.83, 52.68] } },
    { type: 'Feature', properties: { n: 'Irvine', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-4.66, 55.62] } },
    { type: 'Feature', properties: { n: 'Wickford', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.52, 51.61] } },
    { type: 'Feature', properties: { n: 'Hitchin', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.28, 51.95] } },
    { type: 'Feature', properties: { n: 'Letchworth', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.23, 51.98] } },
    { type: 'Feature', properties: { n: 'Huyton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.84, 53.41] } },
    { type: 'Feature', properties: { n: 'Strood', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.48, 51.39] } },
    { type: 'Feature', properties: { n: 'Abingdon', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.28, 51.67] } },
    { type: 'Feature', properties: { n: 'Trowbridge', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.21, 51.32] } },
    { type: 'Feature', properties: { n: 'Glossop', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.95, 53.44] } },
    { type: 'Feature', properties: { n: 'Dumfries', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.60, 55.07] } },
    { type: 'Feature', properties: { n: 'Pontypridd', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.34, 51.60] } },
    { type: 'Feature', properties: { n: 'Stroud', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-2.22, 51.74] } },
    { type: 'Feature', properties: { n: 'Bicester', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.15, 51.90] } },
    { type: 'Feature', properties: { n: 'Winsford', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.52, 53.19] } },
    { type: 'Feature', properties: { n: 'Motherwell', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.99, 55.78] } },
    { type: 'Feature', properties: { n: 'Brighouse', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.79, 53.71] } },
    { type: 'Feature', properties: { n: 'Wigston Magna', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.09, 52.58] } },
    { type: 'Feature', properties: { n: 'Swadlincote', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.56, 52.77] } },
    { type: 'Feature', properties: { n: 'Windsor', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.61, 51.48] } },
    { type: 'Feature', properties: { n: 'Rayleigh', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.60, 51.59] } },
    { type: 'Feature', properties: { n: 'Ecclesfield', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.47, 53.44] } },
    { type: 'Feature', properties: { n: 'Ryde', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.16, 50.73] } },
    { type: 'Feature', properties: { n: 'Earley', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.93, 51.43] } },
    { type: 'Feature', properties: { n: 'Borehamwood', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.27, 51.66] } },
    { type: 'Feature', properties: { n: 'Bexleyheath', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.14, 51.46] } },
    { type: 'Feature', properties: { n: 'Prestwich', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.28, 53.53] } },
    { type: 'Feature', properties: { n: 'Darwen', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.46, 53.70] } },
    { type: 'Feature', properties: { n: 'Epsom', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.27, 51.34] } },
    { type: 'Feature', properties: { n: 'Warwick', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.59, 52.28] } },
    { type: 'Feature', properties: { n: 'Pinner', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.39, 51.59] } },
    { type: 'Feature', properties: { n: 'Rutherglen', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-4.21, 55.83] } },
    { type: 'Feature', properties: { n: 'Loughton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.07, 51.65] } },
    { type: 'Feature', properties: { n: 'Dover', d: 2, s: 6 }, geometry: { type: 'Point', coordinates: [1.31, 51.13] } },
    { type: 'Feature', properties: { n: 'Pontefract', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.31, 53.69] } },
    { type: 'Feature', properties: { n: 'Saint Neots', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.27, 52.23] } },
    { type: 'Feature', properties: { n: 'Bedworth', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.48, 52.48] } },
    { type: 'Feature', properties: { n: 'Burgess Hill', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.13, 50.95] } },
    { type: 'Feature', properties: { n: 'Northolt', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.36, 51.55] } },
    { type: 'Feature', properties: { n: 'Farnworth', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.40, 53.55] } },
    { type: 'Feature', properties: { n: 'Wishaw', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.92, 55.77] } },
    { type: 'Feature', properties: { n: 'Harpenden', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.35, 51.82] } },
    { type: 'Feature', properties: { n: 'Whitstable', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [1.03, 51.36] } },
    { type: 'Feature', properties: { n: 'Deal', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [1.40, 51.22] } },
    { type: 'Feature', properties: { n: 'Radcliffe', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.33, 53.56] } },
    { type: 'Feature', properties: { n: 'Carshalton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.17, 51.37] } },
    { type: 'Feature', properties: { n: 'Plympton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-4.05, 50.39] } },
    { type: 'Feature', properties: { n: 'Bulwell', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.20, 53.00] } },
    { type: 'Feature', properties: { n: 'Cambuslang', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-4.17, 55.82] } },
    { type: 'Feature', properties: { n: 'Sevenoaks', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.19, 51.28] } },
    { type: 'Feature', properties: { n: 'Northfleet', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.34, 51.44] } },
    { type: 'Feature', properties: { n: 'Cramlington', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.59, 55.08] } },
    { type: 'Feature', properties: { n: 'Rushden', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.60, 52.29] } },
    { type: 'Feature', properties: { n: 'Bromsgrove', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.06, 52.34] } },
    { type: 'Feature', properties: { n: 'Nelson', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.22, 53.83] } },
    { type: 'Feature', properties: { n: 'Beverley', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.43, 53.85] } },
    { type: 'Feature', properties: { n: 'Cannock', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.03, 52.69] } },
    { type: 'Feature', properties: { n: 'Hanwell', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.34, 51.52] } },
    { type: 'Feature', properties: { n: 'Stanford le Hope', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.42, 51.51] } },
    { type: 'Feature', properties: { n: 'Kendal', d: 3, s: 6 }, geometry: { type: 'Point', coordinates: [-2.75, 54.33] } },
    { type: 'Feature', properties: { n: 'Willenhall', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.06, 52.58] } },
    { type: 'Feature', properties: { n: 'Wood Green', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.11, 51.60] } },
    { type: 'Feature', properties: { n: 'Heywood', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.22, 53.59] } },
    { type: 'Feature', properties: { n: 'Reddish', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.16, 53.44] } },
    { type: 'Feature', properties: { n: 'Billericay', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.42, 51.63] } },
    { type: 'Feature', properties: { n: 'Darlaston', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.05, 52.57] } },
    { type: 'Feature', properties: { n: 'Littlehampton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.54, 50.81] } },
    { type: 'Feature', properties: { n: 'Ashington', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.57, 55.18] } },
    { type: 'Feature', properties: { n: 'Newton Mearns', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-4.33, 55.77] } },
    { type: 'Feature', properties: { n: 'Yate', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.41, 51.54] } },
    { type: 'Feature', properties: { n: 'Jarrow', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.48, 54.98] } },
    { type: 'Feature', properties: { n: 'Witney', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.49, 51.78] } },
    { type: 'Feature', properties: { n: 'Stratford-upon-Avon', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-1.71, 52.19] } },
    { type: 'Feature', properties: { n: 'Shotley Bridge', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.86, 54.87] } },
    { type: 'Feature', properties: { n: 'Ashford', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.46, 51.43] } },
    { type: 'Feature', properties: { n: 'Ormskirk', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.89, 53.57] } },
    { type: 'Feature', properties: { n: 'Longton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.13, 52.99] } },
    { type: 'Feature', properties: { n: 'Melton Mowbray', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.89, 52.77] } },
    { type: 'Feature', properties: { n: 'Haverhill', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.44, 52.08] } },
    { type: 'Feature', properties: { n: 'Aldridge', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.92, 52.61] } },
    { type: 'Feature', properties: { n: 'Didcot', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.24, 51.61] } },
    { type: 'Feature', properties: { n: 'Clifton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.18, 52.90] } },
    { type: 'Feature', properties: { n: 'Chichester', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.78, 50.84] } },
    { type: 'Feature', properties: { n: 'Hertford', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.08, 51.80] } },
    { type: 'Feature', properties: { n: 'Highbury', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.10, 51.55] } },
    { type: 'Feature', properties: { n: 'Newton Aycliffe', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.58, 54.62] } },
    { type: 'Feature', properties: { n: 'Congleton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.22, 53.16] } },
    { type: 'Feature', properties: { n: 'Cheadle Hulme', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.19, 53.38] } },
    { type: 'Feature', properties: { n: 'East Grinstead', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.01, 51.13] } },
    { type: 'Feature', properties: { n: 'Thatcham', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-1.26, 51.41] } },
    { type: 'Feature', properties: { n: 'Frome', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.32, 51.23] } },
    { type: 'Feature', properties: { n: 'Burntwood', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.92, 52.68] } },
    { type: 'Feature', properties: { n: 'Clydebank', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-4.40, 55.90] } },
    { type: 'Feature', properties: { n: 'Fleetwood', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.02, 53.92] } },
    { type: 'Feature', properties: { n: 'Bournville', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.94, 52.43] } },
    { type: 'Feature', properties: { n: 'Shenley Brook End', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.79, 52.01] } },
    { type: 'Feature', properties: { n: 'Bushey', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.36, 51.64] } },
    { type: 'Feature', properties: { n: 'New Milton', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.65, 50.76] } },
    { type: 'Feature', properties: { n: 'Northfield', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.96, 52.41] } },
    { type: 'Feature', properties: { n: 'Coulsdon', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-0.14, 51.32] } },
    { type: 'Feature', properties: { n: 'Bilston', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.07, 52.57] } },
    { type: 'Feature', properties: { n: 'Wellington', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.52, 52.70] } },
    { type: 'Feature', properties: { n: 'Oldbury', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.02, 52.51] } },
    { type: 'Feature', properties: { n: 'Bishop Auckland', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.68, 54.66] } },
    { type: 'Feature', properties: { n: 'Longbridge', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.98, 52.40] } },
    { type: 'Feature', properties: { n: 'Bloxwich', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.00, 52.61] } },
    { type: 'Feature', properties: { n: 'Upminster', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.25, 51.56] } },
    { type: 'Feature', properties: { n: 'Witham', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.64, 51.80] } },
    { type: 'Feature', properties: { n: 'Workington', d: 3, s: 6 }, geometry: { type: 'Point', coordinates: [-3.55, 54.64] } },
    { type: 'Feature', properties: { n: 'Kingswinford', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.17, 52.50] } },
    { type: 'Feature', properties: { n: 'Rhyl', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.48, 53.32] } },
    { type: 'Feature', properties: { n: 'Daventry', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.16, 52.26] } },
    { type: 'Feature', properties: { n: 'Hindley', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.57, 53.54] } },
    { type: 'Feature', properties: { n: 'Rainham', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.61, 51.36] } },
    { type: 'Feature', properties: { n: 'Portishead', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-2.76, 51.48] } },
    { type: 'Feature', properties: { n: 'Pitsea', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [0.50, 51.57] } },
    { type: 'Feature', properties: { n: 'Thetford', d: 3, s: 6 }, geometry: { type: 'Point', coordinates: [0.74, 52.41] } },
    { type: 'Feature', properties: { n: 'Newport', d: -1, s: 6 }, geometry: { type: 'Point', coordinates: [-1.29, 50.70] } },
    { type: 'Feature', properties: { n: 'Newton Abbot', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-3.61, 50.53] } },
    { type: 'Feature', properties: { n: 'Penzance', d: 3, s: 6 }, geometry: { type: 'Point', coordinates: [-5.54, 50.12] } },
    { type: 'Feature', properties: { n: 'Barnstaple', d: 2, s: 6 }, geometry: { type: 'Point', coordinates: [-4.06, 51.08] } },
    { type: 'Feature', properties: { n: 'Dartford', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [0.22, 51.44] } },
    { type: 'Feature', properties: { n: 'St Austell', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-4.80, 50.34] } },
    { type: 'Feature', properties: { n: 'Northwich', d: 3, s: 6 }, geometry: { type: 'Point', coordinates: [-2.52, 53.26] } },
    { type: 'Feature', properties: { n: 'Goole', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-0.87, 53.70] } },
    { type: 'Feature', properties: { n: 'Fern Down', d: 6, s: 6 }, geometry: { type: 'Point', coordinates: [-1.90, 50.81] } },
    { type: 'Feature', properties: { n: 'Warminster', d: 3, s: 6 }, geometry: { type: 'Point', coordinates: [-2.18, 51.21] } },
    { type: 'Feature', properties: { n: 'Banstead', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-0.20, 51.32] } },
    { type: 'Feature', properties: { n: 'Bordon', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-0.86, 51.11] } },
    { type: 'Feature', properties: { n: 'Weybridge', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-0.45, 51.36] } },
    { type: 'Feature', properties: { n: 'Penrith', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-2.75, 54.66] } },
    { type: 'Feature', properties: { n: 'Selby', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-1.07, 53.78] } },
    { type: 'Feature', properties: { n: 'Skipton', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-2.02, 53.96] } },
    { type: 'Feature', properties: { n: 'Whitby', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-0.62, 54.49] } },
    { type: 'Feature', properties: { n: 'Great Driffield', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-0.44, 54.01] } },
    { type: 'Feature', properties: { n: 'Berwick', d: 3, s: 6 }, geometry: { type: 'Point', coordinates: [-2.01, 55.77] } },
    { type: 'Feature', properties: { n: 'Wells', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-2.65, 51.21] } },
    { type: 'Feature', properties: { n: 'Minehead', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-3.47, 51.20] } },
    { type: 'Feature', properties: { n: 'Hexham', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-2.10, 54.97] } },
    { type: 'Feature', properties: { n: 'Launceston', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-4.36, 50.64] } },
    { type: 'Feature', properties: { n: 'Blandford Forum', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-2.17, 50.85] } },
    { type: 'Feature', properties: { n: 'Richmond', d: 3, s: 6 }, geometry: { type: 'Point', coordinates: [-1.74, 54.40] } },
    { type: 'Feature', properties: { n: 'Keswick', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-3.13, 54.60] } },
    { type: 'Feature', properties: { n: 'Thirsk', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-1.34, 54.23] } },
    { type: 'Feature', properties: { n: 'Malton', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-0.79, 54.14] } },
    { type: 'Feature', properties: { n: 'Ambleside', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-2.96, 54.43] } },
    { type: 'Feature', properties: { n: 'Hawes', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-2.20, 54.30] } },
    { type: 'Feature', properties: { n: 'Alston', d: 4, s: 6 }, geometry: { type: 'Point', coordinates: [-2.44, 54.81] } }
  ]
}

module.exports = {
  method: 'GET',
  path: '/api/places.geojson',
  options: {
    description: 'Get places data',
    handler: async (request, h) => {
      return data
    },
    app: {
      useErrorPages: false
    }
  }
}
