version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    versioning-strategy: lockfile-only
    target-branch: development
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
security_updates_only: true
