module.exports = {
  HTTP_BAD_REQUEST: 400,
  HTTP_NOT_FOUND: 404,
  HTTP_TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  // Station types
  STATION_TYPE_COASTAL: 'C',
  STATION_TYPE_GROUNDWATER: 'G',
  // Flood severity levels
  SEVERITY_VALUE_REMOVED: 4,
  SEVERITY_VALUE_ALERT: 3,
  SEVERITY_VALUE_WARNING: 2,
  SEVERITY_VALUE_SEVERE: 3,
  // Risk levels
  RISK_LEVEL_VERY_LOW: 1,
  RISK_LEVEL_LOW: 2,
  RISK_LEVEL_MEDIUM: 3,
  RISK_LEVEL_HIGH: 4,
  // Percentile threshold for high levels
  HIGH_LEVEL_PERCENTILE_THRESHOLD: 5,
  // Outlook days
  OUTLOOK_DAYS_COUNT: 5,
  // Day index constants
  DAY_INDEX_OUTLOOK_START: 2,
  DAY_INDEX_3: 3,
  DAY_INDEX_4: 4,
  DAYS_TO_SHIFT_YESTERDAY: 1,
  DAYS_TO_SHIFT_DAY_BEFORE_YESTERDAY: 2,
  // Trend constants
  TREND_REMAINS: 'remains',
  // Group by message day indices
  GROUP_BY_DAY_0: '0',
  GROUP_BY_DAY_1: '1',
  GROUP_BY_DAY_2: '2',
  GROUP_BY_DAY_3: '3',
  GROUP_BY_DAY_4: '4'
}
