const COORDINATE_PATTERN = /^[-+]?\d+(\.\d+)?,[-+]?\d+(\.\d+)?$/

module.exports = {
  HTTP_MOVED_PERMANENTLY: 301,
  HTTP_BAD_REQUEST: 400,
  HTTP_NOT_FOUND: 404,
  HTTP_TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  COORDINATE_PATTERN
}
