name: PR Base Branch Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    steps:
      - name: Validate base branch against GitFlow rules
        env:
          BASE: ${{ github.event.pull_request.base.ref }}   # e.g. master, development
          HEAD: ${{ github.event.pull_request.head.ref }}   # e.g. feature/FSR-****, release/1.2.0
        run: |
          echo "PR: $HEAD  →  $BASE"

          fail() { echo "$1"; exit 1; }

          case "$BASE" in
            master)
              # Only release/* or hotfix/* may target master
              if [[ "$HEAD" == release/* || "$HEAD" == hotfix/* ]]; then
                echo "Allowed: $HEAD → master"
              else
                fail "Only release/* or hotfix/* branches may target master."
              fi
              ;;
            development)
              # Allow feature/*, hotfix/* (back-merge), and release/* (back-merge)
              if [[ "$HEAD" == feature/* || "$HEAD" == hotfix/* || "$HEAD" == release/* ]]; then
                echo "Allowed: $HEAD → development"
              else
                fail "Only feature/*, hotfix/*, or release/* may target development."
              fi
              ;;
            *)
              # For other bases (rare), allow but warn; or fail if you prefer strictness
              echo "ℹBase '$BASE' is not enforced by policy. (You can make this a failure if needed.)"
              ;;
          esac

          echo "Branches OK per policy."
